-- liquibase formatted sql

-- changeset init:1
CREATE TABLE hotels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    brand VARCHAR(255) NOT NULL,
    house_number VARCHAR(20),
    street VARCHAR(255),
    city VARCHAR(255),
    country VARCHAR(255),
    post_code VARCHAR(20),
    phone VARCHAR(50),
    email VARCHAR(255),
    check_in VARCHAR(10),
    check_out VARCHAR(10)
);
